# Generated by Django 5.2.11 on 2026-03-05 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0007_household_postal_timezone'),
        ('projects', '0003_add_project_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPinnedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_projects', to='households.householdmember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by_members', to='projects.project')),
            ],
            options={
                'db_table': 'project_member_pins',
                'indexes': [models.Index(fields=['household_member'], name='user_pinned_househo_ce4d75_idx'), models.Index(fields=['project'], name='user_pinned_project_b643ce_idx')],
                'unique_together': {('household_member', 'project')},
            },
        ),
    ]
