# Generated by Django 5.2.11 on 2026-03-05 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_userpinnedproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_pinned',
        ),
    ]
