# Generated by Django 5.2.11 on 2026-07-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_user_pinned_househo_ce4d75_idx_project_mem_househo_b9a7c5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectaithread',
            name='household',
        ),
        migrations.RemoveField(
            model_name='projectaithread',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectaithread',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProjectAIMessage',
        ),
        migrations.DeleteModel(
            name='ProjectAIThread',
        ),
    ]
