# Generated by Django 5.2.12 on 2026-03-12 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0007_household_postal_timezone'),
        ('interactions', '0012_add_occurred_at_check_constraint'),
        ('projects', '0006_rename_user_pinned_househo_ce4d75_idx_project_mem_househo_b9a7c5_idx_and_more'),
        ('zones', '0003_add_zone_color_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('archived', 'Archived')], default='pending', max_length=50)),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'Haute'), (2, 'Normale'), (3, 'Basse')], default=2, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, db_column='completed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.project')),
                ('source_interaction', models.ForeignKey(blank=True, db_column='source_interaction_id', help_text='Interaction this task was created from (or migrated from)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_tasks', to='interactions.interaction')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('zone', models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.CASCADE, to='zones.zone')),
            ],
            options={
                'db_table': 'task_zones',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='zones',
            field=models.ManyToManyField(related_name='tasks', through='tasks.TaskZone', to='zones.zone'),
        ),
        migrations.AddIndex(
            model_name='taskzone',
            index=models.Index(fields=['task'], name='task_zones_task_id_3c1fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='taskzone',
            index=models.Index(fields=['zone'], name='task_zones_zone_id_73cb46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskzone',
            unique_together={('task', 'zone')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['household', 'status'], name='idx_task_hh_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['household', 'due_date'], name='idx_task_hh_due'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='idx_task_assigned'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project'], name='idx_task_project'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['backlog', 'pending', 'in_progress', 'done', 'archived'])), name='tasks_status_check'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('priority__isnull', True), ('priority__in', [1, 2, 3]), _connector='OR'), name='tasks_priority_check'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_by__isnull', False), _connector='OR'), name='tasks_completed_integrity'),
        ),
    ]
