# Generated by Django 5.2.11 on 2026-03-19 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options'),
        ('interactions', '0012_add_occurred_at_check_constraint'),
        ('tasks', '0002_migrate_todos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_documents', to='documents.document')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_documents', to='tasks.task')),
            ],
            options={
                'db_table': 'task_documents',
                'unique_together': {('task', 'document')},
            },
        ),
        migrations.CreateModel(
            name='TaskInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='interactions.interaction')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_interactions', to='tasks.task')),
            ],
            options={
                'db_table': 'task_interactions',
                'unique_together': {('task', 'interaction')},
            },
        ),
    ]
