# Generated by Django 5.2.11 on 2026-03-19 15:59

from django.conf import settings
from django.db import migrations, models


def clear_assignee_on_private_tasks(apps, schema_editor):
    """Retire l'assignation des tâches privées existantes pour respecter la nouvelle contrainte."""
    Task = apps.get_model('tasks', 'Task')
    Task.objects.filter(is_private=True, assigned_to__isnull=False).update(assigned_to=None)


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0007_household_postal_timezone'),
        ('interactions', '0012_add_occurred_at_check_constraint'),
        ('projects', '0006_rename_user_pinned_househo_ce4d75_idx_project_mem_househo_b9a7c5_idx_and_more'),
        ('tasks', '0003_taskdocument_taskinteraction'),
        ('zones', '0003_add_zone_color_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            clear_assignee_on_private_tasks,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(
                condition=models.Q(('is_private', False), ('assigned_to__isnull', True), _connector='OR'),
                name='tasks_private_not_assigned',
            ),
        ),
    ]
