# Generated by Django 5.2.11 on 2026-07-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_private_not_assigned_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='needs_dry_weather',
            field=models.BooleanField(default=False),
        ),
    ]
