# Generated by Django 5.2.11 on 2026-07-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_needs_dry_weather'),
        ('documents', '0006_backfill_document_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDocument',
        ),
    ]
