# Generated by Django 5.2.11 on 2026-02-11 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(blank=True, help_text="URL to user's avatar image", max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name shown in the UI', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='en', help_text="User's preferred language", max_length=10),
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the household', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True, default='', help_text='Physical address of the household')),
                ('city', models.CharField(blank=True, default='', help_text='City where the household is located', max_length=100)),
                ('country', models.CharField(blank=True, default='', help_text='Country where the household is located', max_length=100)),
                ('context_notes', models.TextField(blank=True, default='', help_text='General notes and context about the household')),
                ('ai_prompt_context', models.TextField(blank=True, default='', help_text='Specific context information to include in AI prompts for better responses')),
                ('inbound_email_alias', models.CharField(blank=True, help_text='Email alias for receiving documents/quotes by email', max_length=255, null=True, unique=True)),
                ('default_household', models.BooleanField(default=False, help_text='Indicates if this household is the default for email processing')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city'], name='idx_household_city'), models.Index(fields=['country'], name='idx_household_country'), models.Index(fields=['inbound_email_alias'], name='idx_household_email')],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['household', 'user'], name='idx_household_user'), models.Index(fields=['user'], name='idx_member_user')],
                'unique_together': {('household', 'user')},
            },
        ),
    ]
