# Generated by Django 5.2.11 on 2026-02-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_color_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch'), ('es', 'Español')], default='en', help_text="User's preferred language", max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', help_text="User's preferred theme (light/dark/system)", max_length=20),
        ),
    ]
