# Generated by Django 5.2.11 on 2026-02-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_active_household'),
        ('accounts', '0005_remove_householdmember_household_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
    ]
