# Generated by Django 5.2.11 on 2026-03-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_avatar_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='householdmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='household',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Household',
        ),
        migrations.DeleteModel(
            name='HouseholdMember',
        ),
    ]
