# Generated by Django 5.2.11 on 2026-03-19 22:18

from django.db import migrations, models


def reset_default_locale(apps, schema_editor):
    """
    Reset locale='en' to None for all users.
    Since the locale was never actually applied at login (bug in me_view),
    'en' was always just the model default — never an explicit user choice.
    Setting to None makes the frontend fall back to browser language detection.
    """
    User = apps.get_model('accounts', 'User')
    User.objects.filter(locale='en').update(locale=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_householdmember_household_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch'), ('es', 'Español')], default=None, help_text="User's preferred language. Null means use browser detection.", max_length=10, null=True),
        ),
        migrations.RunPython(reset_default_locale, migrations.RunPython.noop),
    ]
