# Generated by Django 5.2.11 on 2026-03-20 20:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_locale_nullable_browser_fallback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text="User's avatar image file", null=True, upload_to=accounts.models.User._avatar_upload_path),
        ),
    ]
