# Generated by Django 5.2.11 on 2026-07-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_avatar_upload_path_and_document_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_memory_enabled',
            field=models.BooleanField(default=True, help_text="When enabled, the AI agent automatically remembers durable facts about the user from conversations and uses them in its answers. When disabled, memories are neither captured automatically nor injected; explicit 'remember that…' requests still work."),
        ),
    ]
