# Generated by Django 5.2.11 on 2026-07-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_agent_memory_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pinned_modules',
            field=models.JSONField(blank=True, default=list, help_text='Sidebar module keys pinned by the user, in order.'),
        ),
    ]
