# Generated by Django 5.2.11 on 2026-07-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_pinned_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="completed_tutorials",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tutorial keys the user has completed.",
            ),
        ),
    ]
