# Generated by Django 5.2.11 on 2026-07-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_completed_tutorials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='digest_disabled_sections',
            field=models.JSONField(blank=True, default=list, help_text='Daily-digest section keys the user turned off.'),
        ),
    ]
