# Generated by Django 5.2.11 on 2026-07-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_pinned_modules_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recap_disabled_chapters',
            field=models.JSONField(blank=True, default=list, help_text='Monthly-recap chapter keys the user turned off.'),
        ),
    ]
