# Generated by Django 5.2.11 on 2026-07-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_recap_disabled_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='muted_notification_types',
            field=models.JSONField(blank=True, default=list, help_text='Notification types the user does not want to receive.'),
        ),
    ]
