# Generated by Django 5.2.11 on 2026-08-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_pinned_modules_money_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recap_dismissed_month',
            field=models.CharField(blank=True, default='', help_text="Month ('YYYY-MM') whose recap teaser the user dismissed.", max_length=7),
        ),
    ]
