# Generated by Django 5.2.11 on 2026-08-15 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0012_invitation_shareable_link'),
        ('zones', '0008_zone_qr_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('done', 'done'), ('abandoned', 'abandoned')], default='draft', max_length=16)),
                ('treasure_text', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunts_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'treasure hunt',
                'verbose_name_plural': 'treasure hunts',
                'db_table': 'games_hunts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HuntStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('riddle', models.TextField(blank=True, default='')),
                ('found_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='games.hunt')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hunt_steps', to='zones.zone')),
            ],
            options={
                'verbose_name': 'hunt step',
                'verbose_name_plural': 'hunt steps',
                'db_table': 'games_hunt_steps',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='hunt',
            index=models.Index(fields=['household', 'status'], name='games_hunts_househo_5cff96_idx'),
        ),
        migrations.AddConstraint(
            model_name='hunt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('household',), name='games_one_active_hunt_per_household'),
        ),
        migrations.AddIndex(
            model_name='huntstep',
            index=models.Index(fields=['hunt', 'position'], name='games_hunt__hunt_id_3996bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='huntstep',
            unique_together={('hunt', 'position')},
        ),
    ]
