# Generated by Django 5.2.11 on 2026-07-05 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('households', '0008_household_preferred_language'),
        ('projects', '0007_remove_projectaithread_household_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('emoji', models.CharField(blank=True, default='', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('target_object_id', models.UUIDField(blank=True, help_text='Polymorphic target: id of the entity this tracker is about.', null=True)),
                ('last_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('last_entry_at', models.DateTimeField(blank=True, null=True)),
                ('entries_summary', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackers', to='projects.project')),
                ('target_content_type', models.ForeignKey(blank=True, help_text='Polymorphic target: type of the entity this tracker is about.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trackers',
                'ordering': ['-last_entry_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrackerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('occurred_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('tracker', models.ForeignKey(db_column='tracker_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trackers.tracker')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'tracker entries',
                'db_table': 'tracker_entries',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['household', 'is_active'], name='idx_tracker_hh_active'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['project'], name='idx_tracker_project'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='idx_tracker_target'),
        ),
        migrations.AddConstraint(
            model_name='tracker',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_content_type__isnull', True), ('target_object_id__isnull', True)), models.Q(('target_content_type__isnull', False), ('target_object_id__isnull', False)), _connector='OR'), name='tracker_target_integrity'),
        ),
        migrations.AddIndex(
            model_name='trackerentry',
            index=models.Index(fields=['tracker', '-occurred_at'], name='idx_tent_tracker_date'),
        ),
    ]
