# Generated by Django 5.2.11 on 2026-07-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='kind',
            field=models.CharField(choices=[('measure', 'Measure'), ('consumption', 'Consumption')], default='measure', max_length=16),
        ),
        migrations.AddField(
            model_name='tracker',
            name='rate_per_day',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='reserve',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
