# Generated by Django 5.2.11 on 2026-07-12 11:26
#
# Lot 7 (PARCOURS_11_LOT7): the consumption kind is removed — dropping the
# columns converts existing consumption trackers to plain measure ones, their
# entry history untouched. The final RunPython rebuilds every entries_summary
# so the RAG text loses its rate/reserve/runway header.

from django.db import migrations


def _rebuild_entries_summaries(apps, schema_editor):
    # Uses the real model + service on purpose: this migration matches the
    # final schema, and the summary rendering lives in trackers.services.
    from trackers.models import Tracker
    from trackers.services import refresh_tracker_cache

    for tracker in Tracker.objects.all().iterator():
        refresh_tracker_cache(tracker)


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_tracker_kind_tracker_rate_per_day_tracker_reserve'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tracker',
            name='tracker_target_integrity',
        ),
        migrations.RemoveIndex(
            model_name='tracker',
            name='idx_tracker_target',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='rate_per_day',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='reserve',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='target_content_type',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='target_object_id',
        ),
        migrations.RunPython(_rebuild_entries_summaries, migrations.RunPython.noop),
    ]
