# Generated by Django 5.2.11 on 2026-07-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconversation',
            name='context_entity_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='context_object_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
