# Generated by Django 5.2.11 on 2026-07-03 11:46

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentconversation_context_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentconversation',
            options={'ordering': [models.OrderBy(django.db.models.functions.comparison.Coalesce('last_message_at', 'created_at'), descending=True), '-created_at']},
        ),
    ]
