# Generated by Django 5.2.11 on 2026-07-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_agentmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconversation',
            name='pinned_contexts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
