# Generated by Django 5.2.11 on 2026-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_agentconversation_pinned_contexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconversation',
            name='web_search_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
