# Generated by Django 5.2.11 on 2026-07-21 09:03

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_pgvector_extension'),
        ('households', '0010_household_latitude_household_location_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('model', models.CharField(max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['household', 'entity_type', 'object_id'], name='idx_embchunk_hh_source'), models.Index(fields=['entity_type', 'object_id'], name='idx_embchunk_source')],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'object_id', 'chunk_index'), name='uq_embedding_chunk_source_pos')],
            },
        ),
    ]
