# Generated by Django 5.2.11 on 2026-02-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['last_name', 'first_name', 'created_at'], 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
    ]
