# Generated by Django 5.2.11 on 2026-03-04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceContract",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("provider", models.TextField(blank=True, default="")),
                ("contract_number", models.TextField(blank=True, default="")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("health", "Health"),
                            ("home", "Home"),
                            ("car", "Car"),
                            ("life", "Life"),
                            ("liability", "Liability"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("insured_item", models.TextField(blank=True, default="")),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended"), ("terminated", "Terminated")],
                        default="active",
                        max_length=32,
                    ),
                ),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("quarterly", "Quarterly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=32,
                    ),
                ),
                ("monthly_cost", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("yearly_cost", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("coverage_summary", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        db_column="household_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="households.household",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "insurance contract",
                "verbose_name_plural": "insurance contracts",
                "db_table": "insurance_contracts",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="insurancecontract",
            index=models.Index(fields=["household"], name="idx_insurance_hh"),
        ),
        migrations.AddIndex(
            model_name="insurancecontract",
            index=models.Index(fields=["household", "type"], name="idx_insurance_hh_type"),
        ),
        migrations.AddIndex(
            model_name="insurancecontract",
            index=models.Index(fields=["household", "status"], name="idx_insurance_hh_status"),
        ),
        migrations.AddIndex(
            model_name="insurancecontract",
            index=models.Index(fields=["renewal_date"], name="idx_insurance_renewal"),
        ),
        migrations.AddConstraint(
            model_name="insurancecontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_cost__gte", 0), ("yearly_cost__gte", 0)),
                name="insurance_costs_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="insurancecontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__isnull", True), ("end_date__isnull", True), _connector="OR")
                | models.Q(("end_date__gte", models.F("start_date"))),
                name="insurance_dates_consistent",
            ),
        ),
    ]
