# Generated by Django 5.2.11 on 2026-02-15 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_interaction_document_idx_docs_interaction'),
        ('households', '0001_initial'),
        ('interactions', '0004_interactiondocument'),
        ('projects', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['project'], name='idx_int_project'),
        ),
        migrations.AddField(
            model_name='interactiondocument',
            name='document',
            field=models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='interaction_documents', to='documents.document'),
        ),
        migrations.AddField(
            model_name='interactiondocument',
            name='interaction',
            field=models.ForeignKey(db_column='interaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='interaction_documents', to='interactions.interaction'),
        ),
        migrations.AddIndex(
            model_name='interactiondocument',
            index=models.Index(fields=['interaction'], name='interaction_interac_98c33b_idx'),
        ),
        migrations.AddIndex(
            model_name='interactiondocument',
            index=models.Index(fields=['document'], name='interaction_documen_8c8aa1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interactiondocument',
            unique_together={('interaction', 'document')},
        ),
    ]
