# Generated by Django 5.2.11 on 2026-03-04

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
        ("zones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("color", models.CharField(default="#94a3b8", max_length=16)),
                ("emoji", models.CharField(default="📦", max_length=16)),
                ("description", models.TextField(default="")),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        db_column="household_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="households.household",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "stock category",
                "verbose_name_plural": "stock categories",
                "db_table": "stock_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField(default="")),
                ("sku", models.TextField(blank=True, default="")),
                ("barcode", models.TextField(blank=True, default="")),
                ("quantity", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("unit", models.CharField(default="unit", max_length=32)),
                ("min_quantity", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("max_quantity", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("unit_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("last_restocked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In stock"),
                            ("low_stock", "Low stock"),
                            ("out_of_stock", "Out of stock"),
                            ("ordered", "Ordered"),
                            ("expired", "Expired"),
                            ("reserved", "Reserved"),
                        ],
                        default="in_stock",
                        max_length=32,
                    ),
                ),
                ("supplier", models.TextField(blank=True, default="")),
                ("notes", models.TextField(default="")),
                ("tags", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        db_column="household_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="households.household",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="stock.stockcategory"),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_items",
                        to="zones.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock item",
                "verbose_name_plural": "stock items",
                "db_table": "stock_items",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="stockcategory",
            index=models.Index(fields=["household", "name"], name="idx_stock_cat_hh_name"),
        ),
        migrations.AlterUniqueTogether(
            name="stockcategory",
            unique_together={("household", "name")},
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(fields=["household", "status"], name="idx_stock_item_hh_status"),
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(fields=["household", "category"], name="idx_stock_item_hh_cat"),
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(fields=["zone"], name="idx_stock_item_zone"),
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(fields=["expiration_date"], name="idx_stock_item_exp"),
        ),
    ]
