# Generated by Django 5.2.11 on 2026-07-15 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0010_household_latitude_household_location_label_and_more'),
        ('interactions', '0019_remove_interaction_interactions_type_check_and_more'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLevelReading',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_at', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('kind', models.CharField(choices=[('inventory', 'Inventory count'), ('purchase', 'Post-purchase level')], default='inventory', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('source_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_level_readings', to='interactions.interaction')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_readings', to='stock.stockitem')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stock level reading',
                'verbose_name_plural': 'stock level readings',
                'db_table': 'stock_level_readings',
                'ordering': ['reading_at'],
                'indexes': [models.Index(fields=['stock_item', 'reading_at'], name='idx_stock_reading_item_at')],
            },
        ),
    ]
