# Generated by Django 5.2.11 on 2026-07-23 20:22

from django.db import migrations, models


def reclassify_retired_statuses(apps, schema_editor):
    """Reclassify items still on a retired status (ordered/reserved/expired).

    The status is now fully derived from quantity/min_quantity. Any row left on a
    removed value is recomputed to a valid one so the enum stays coherent.
    """
    StockItem = apps.get_model('stock', 'StockItem')
    retired = ['ordered', 'reserved', 'expired']
    for item in StockItem.objects.filter(status__in=retired):
        if item.quantity <= 0:
            item.status = 'out_of_stock'
        elif item.min_quantity is not None and item.quantity <= item.min_quantity:
            item.status = 'low_stock'
        else:
            item.status = 'in_stock'
        item.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stocklevelreading'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockitem',
            name='idx_stock_item_exp',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='expiration_date',
        ),
        migrations.RunPython(reclassify_retired_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('low_stock', 'Low stock'), ('out_of_stock', 'Out of stock')], default='in_stock', max_length=32),
        ),
    ]
