# Generated by Django 5.2.11 on 2026-02-13 22:41

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('note', 'Note'), ('todo', 'Todo'), ('expense', 'Expense'), ('maintenance', 'Maintenance'), ('repair', 'Repair'), ('installation', 'Installation'), ('inspection', 'Inspection'), ('warranty', 'Warranty'), ('issue', 'Issue'), ('upgrade', 'Upgrade'), ('replacement', 'Replacement'), ('disposal', 'Disposal')], default='note', max_length=50)),
                ('status', models.CharField(blank=True, choices=[('backlog', 'Backlog'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('archived', 'Archived')], help_text='Status (mainly for todos)', max_length=50, null=True)),
                ('occurred_at', models.DateTimeField(help_text='When this interaction occurred')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Tags for categorization', size=None)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Expense amounts, vendor info, etc.')),
                ('enriched_text', models.TextField(blank=True, help_text='Full-text searchable content with OCR from documents')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interactions',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractionZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction', models.ForeignKey(db_column='interaction_id', on_delete=django.db.models.deletion.CASCADE, to='interactions.interaction')),
                ('zone', models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.CASCADE, to='zones.zone')),
            ],
            options={
                'db_table': 'interaction_zones',
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='zones',
            field=models.ManyToManyField(related_name='interactions', through='interactions.InteractionZone', to='zones.zone'),
        ),
        migrations.AddIndex(
            model_name='interactionzone',
            index=models.Index(fields=['interaction'], name='interaction_interac_fb4a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionzone',
            index=models.Index(fields=['zone'], name='interaction_zone_id_93773f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interactionzone',
            unique_together={('interaction', 'zone')},
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['household', 'type'], name='idx_int_hh_type'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['household', '-occurred_at'], name='idx_int_hh_date'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['status'], name='idx_int_status'),
        ),
    ]
