# Generated by Django 5.2.11 on 2026-02-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_squashed_contacts_0004_structure'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, related_name='interaction_contacts', to='directory.contact')),
                ('interaction', models.ForeignKey(db_column='interaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='interaction_contacts', to='interactions.interaction')),
            ],
            options={
                'db_table': 'interaction_contacts',
            },
        ),
        migrations.CreateModel(
            name='InteractionStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interaction', models.ForeignKey(db_column='interaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='interaction_structures', to='interactions.interaction')),
            ],
            options={
                'db_table': 'interaction_structures',
            },
        ),
    ]
