# Generated by Django 5.2.11 on 2026-02-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_interactioncontact_interactionstructure'),
        ('directory', '0005_squashed_contacts_0004_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionstructure',
            name='structure',
            field=models.ForeignKey(db_column='structure_id', on_delete=django.db.models.deletion.CASCADE, related_name='interaction_structures', to='directory.structure'),
        ),
        migrations.AddIndex(
            model_name='interactioncontact',
            index=models.Index(fields=['interaction'], name='interaction_interac_96aac1_idx'),
        ),
        migrations.AddIndex(
            model_name='interactioncontact',
            index=models.Index(fields=['contact'], name='interaction_contact_7a6614_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interactioncontact',
            unique_together={('interaction', 'contact')},
        ),
        migrations.AddIndex(
            model_name='interactionstructure',
            index=models.Index(fields=['interaction'], name='interaction_interac_95e821_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionstructure',
            index=models.Index(fields=['structure'], name='interaction_structu_91fb5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interactionstructure',
            unique_together={('interaction', 'structure')},
        ),
    ]
