# Generated by Django 5.2.11 on 2026-02-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_interactionstructure_structure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(default='attachment')),
                ('note', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interaction_documents',
            },
        ),
    ]
