# Generated by Django 5.2.11 on 2026-02-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_interaction_project_interaction_idx_int_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-occurred_at'], 'verbose_name': 'interaction', 'verbose_name_plural': 'interactions'},
        ),
    ]
