# Generated by Django 5.2.12 on 2026-03-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0010_add_interaction_type_status_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='occurred_at',
            field=models.DateTimeField(blank=True, help_text='When this interaction occurred', null=True),
        ),
    ]
