# Generated by Django 5.2.12 on 2026-03-12 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0007_household_postal_timezone'),
        ('interactions', '0011_make_occurred_at_nullable'),
        ('projects', '0006_rename_user_pinned_househo_ce4d75_idx_project_mem_househo_b9a7c5_idx_and_more'),
        ('zones', '0003_add_zone_color_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'todo'), ('occurred_at__isnull', False), _connector='OR'), name='interactions_occurred_at_required_for_non_todo'),
        ),
    ]
