# Generated by Django 5.2.11 on 2026-05-02 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0008_household_preferred_language'),
        ('interactions', '0012_add_occurred_at_check_constraint'),
        ('projects', '0006_rename_user_pinned_househo_ce4d75_idx_project_mem_househo_b9a7c5_idx_and_more'),
        ('stock', '0001_initial'),
        ('zones', '0005_zone_one_root_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='stock_item',
            field=models.ForeignKey(blank=True, db_column='stock_item_id', help_text='Optional link to a stock item (e.g. an expense for restocking).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='stock.stockitem'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['stock_item'], name='idx_int_stock_item'),
        ),
    ]
