# Generated by Django 5.2.11 on 2026-07-11 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('households', '0008_household_preferred_language'),
        ('interactions', '0018_purge_todo_interactions'),
        ('zones', '0005_zone_one_root_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='interaction',
            name='interactions_type_check',
        ),
        migrations.RemoveConstraint(
            model_name='interaction',
            name='interactions_status_check',
        ),
        migrations.RemoveConstraint(
            model_name='interaction',
            name='interactions_occurred_at_required_for_non_todo',
        ),
        migrations.RemoveIndex(
            model_name='interaction',
            name='idx_int_status',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='status',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('note', 'Note'), ('expense', 'Expense'), ('maintenance', 'Maintenance'), ('repair', 'Repair'), ('installation', 'Installation'), ('inspection', 'Inspection'), ('warranty', 'Warranty'), ('issue', 'Issue'), ('upgrade', 'Upgrade'), ('replacement', 'Replacement'), ('disposal', 'Disposal')], default='note', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['note', 'expense', 'maintenance', 'repair', 'installation', 'inspection', 'warranty', 'issue', 'upgrade', 'replacement', 'disposal'])), name='interactions_type_check'),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.CheckConstraint(condition=models.Q(('occurred_at__isnull', False)), name='interactions_occurred_at_required'),
        ),
    ]
