# Generated by Django 5.2.11 on 2026-07-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0019_remove_interaction_interactions_type_check_and_more'),
        ('documents', '0006_backfill_document_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InteractionDocument',
        ),
    ]
