# Generated by Django 5.2.11 on 2026-07-16 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('interactions', '0020_delete_interactiondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='budget',
            field=models.ForeignKey(blank=True, help_text="Optional monthly budget this expense counts against (parcours 21). Only meaningful for type='expense'; null = hors budget. Deleting the budget resets this to null, never deletes the expense.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='budget.budget'),
        ),
    ]
