# Generated by Django 5.2.11 on 2026-07-24 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budgetreport'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('households', '0010_household_latitude_household_location_label_and_more'),
        ('interactions', '0021_interaction_budget'),
        ('zones', '0006_delete_zonedocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Expense amount. Only for type='expense'; null otherwise.", max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='kind',
            field=models.CharField(blank=True, default='', help_text='Expense discriminator (stock_purchase, equipment_purchase, project_purchase, chickens_purchase, manual, recurring). Empty for non-expense interactions.', max_length=50),
        ),
        migrations.AddField(
            model_name='interaction',
            name='supplier',
            field=models.CharField(blank=True, default='', help_text='Expense vendor/supplier. Empty when not applicable.', max_length=255),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Feature-specific extras (delta, unit, brand, recurring_id…). Structured money fields are now real columns (amount/kind/supplier).'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['household', 'kind'], name='idx_int_hh_kind'),
        ),
    ]
