# Generated by Django 5.2.11 on 2026-07-26 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_banktransaction_options_and_more'),
        ('budget', '0003_budgetreport'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('households', '0010_household_latitude_household_location_label_and_more'),
        ('interactions', '0024_strip_expense_metadata_keys'),
        ('zones', '0006_delete_zonedocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, help_text="Bank statement line this expense is an allocation of (parcours 25). There is NO Allocation table: a line split 80/40 simply carries two expenses, each with its own amount and budget. `amount` therefore stays a scalar column and the project's nine Sum('amount') aggregations are untouched. SET_NULL: deleting the bank line never destroys a journalled fact.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='banking.banktransaction'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='reconciled_by',
            field=models.CharField(blank=True, choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='', help_text='How this expense got attached to its bank line.', max_length=6),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(condition=models.Q(('bank_transaction__isnull', True), ('type', 'expense')), fields=['household', 'amount'], name='idx_int_unreconciled_amount'),
        ),
    ]
