# Generated by Django 5.2.11 on 2026-07-26 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_banktransaction_inflow_nature'),
        ('budget', '0003_budgetreport'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('households', '0011_retire_banking_module_key'),
        ('interactions', '0025_interaction_bank_transaction_and_more'),
        ('zones', '0006_delete_zonedocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='recurring_expense',
            field=models.ForeignKey(blank=True, help_text="The recurrence this expense materializes (parcours 26, lot 6). Promoted out of metadata['recurring_id'] because the conformity control has to GROUP BY it — and CLAUDE.md forbids querying metadata: a JSON key can be neither indexed nor constrained. The JSON key is kept for display.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='budget.recurringexpense'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(condition=models.Q(('recurring_expense__isnull', False)), fields=['recurring_expense', 'occurred_at'], name='idx_int_recurring_occurrence'),
        ),
    ]
