# Generated by Django 5.2.11 on 2026-07-29 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0012_invitation_shareable_link'),
        ('interactions', '0028_promote_misplaced_expense_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('normalized_name', models.CharField(editable=False, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'db_table': 'suppliers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['household', 'name'], name='idx_supplier_hh_name')],
                'constraints': [models.UniqueConstraint(fields=('household', 'normalized_name'), name='suppliers_unique_per_household')],
            },
        ),
    ]
