# Generated by Django 5.2.11 on 2026-02-15 21:19

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        ('interactions', '0003_interactionstructure_structure_and_more'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('category', models.TextField(default='general')),
                ('manufacturer', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('serial_number', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_vendor', models.TextField(blank=True, null=True)),
                ('warranty_expires_on', models.DateField(blank=True, null=True)),
                ('warranty_provider', models.TextField(blank=True, null=True)),
                ('warranty_notes', models.TextField(default='')),
                ('maintenance_interval_months', models.IntegerField(blank=True, null=True)),
                ('last_service_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('storage', 'Storage'), ('retired', 'Retired'), ('lost', 'Lost'), ('ordered', 'Ordered')], default='active', max_length=32)),
                ('condition', models.TextField(blank=True, default='good')),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('retired_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(default='')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='zones.zone')),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(default='log')),
                ('note', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_interactions', to='equipment.equipment')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_interactions', to='interactions.interaction')),
            ],
            options={
                'db_table': 'equipment_interactions',
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['household', 'status'], name='idx_equipment_hh_status'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['zone'], name='idx_equipment_zone'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentinteraction',
            unique_together={('equipment', 'interaction')},
        ),
    ]
