# Generated by Django 5.2.11 on 2026-03-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warranty_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
