# Generated by Django 5.2.11 on 2026-07-11 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0008_household_preferred_language'),
        ('trackers', '0002_tracker_kind_tracker_rate_per_day_tracker_reserve'),
        ('zones', '0005_zone_one_root_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('breed', models.CharField(blank=True, default='', max_length=200)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('hatched_on', models.DateField(blank=True, null=True)),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('broody', 'Broody'), ('sick', 'Sick'), ('deceased', 'Deceased'), ('gone', 'Gone')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, db_column='zone_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='zones.zone')),
            ],
            options={
                'db_table': 'chickens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChickenEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('arrival', 'Arrival'), ('care', 'Care'), ('illness', 'Illness'), ('broody', 'Broody'), ('molt', 'Molt'), ('predator', 'Predator'), ('death', 'Death'), ('departure', 'Departure'), ('other', 'Other')], max_length=20)),
                ('occurred_on', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True, default='')),
                ('chicken', models.ForeignKey(blank=True, db_column='chicken_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chickens.chicken')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chicken_events',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChickenSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('feed_tracker', models.ForeignKey(blank=True, db_column='feed_tracker_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trackers.tracker')),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chicken_settings',
            },
        ),
        migrations.CreateModel(
            name='EggLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chicken_egg_logs',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='chicken',
            index=models.Index(fields=['household', 'status'], name='idx_chicken_hh_status'),
        ),
        migrations.AddConstraint(
            model_name='chicken',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'broody', 'sick', 'deceased', 'gone'])), name='chickens_status_check'),
        ),
        migrations.AddIndex(
            model_name='chickenevent',
            index=models.Index(fields=['household', 'occurred_on'], name='idx_ck_event_hh_date'),
        ),
        migrations.AddIndex(
            model_name='chickenevent',
            index=models.Index(fields=['chicken'], name='idx_ck_event_chicken'),
        ),
        migrations.AddConstraint(
            model_name='chickensettings',
            constraint=models.UniqueConstraint(fields=('household',), name='uniq_chicken_settings_hh'),
        ),
        migrations.AddIndex(
            model_name='egglog',
            index=models.Index(fields=['household', 'date'], name='idx_egg_log_hh_date'),
        ),
        migrations.AddConstraint(
            model_name='egglog',
            constraint=models.UniqueConstraint(fields=('household', 'date'), name='uniq_egg_log_hh_date'),
        ),
    ]
