# Generated by Django 5.2.11 on 2026-07-12 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chickensettings',
            name='feed_tracker',
        ),
        migrations.AddField(
            model_name='chickensettings',
            name='feed_stock_item',
            field=models.ForeignKey(blank=True, db_column='feed_stock_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.stockitem'),
        ),
    ]
