# Generated by Django 5.2.11 on 2026-08-01 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0002_remove_chickensettings_feed_tracker_and_more'),
        ('households', '0012_invitation_shareable_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenChore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('emoji', models.CharField(blank=True, default='', max_length=16)),
                ('interval_days', models.PositiveIntegerField(help_text='Days between two occurrences — also the delay after which the reminder fires.')),
                ('starts_on', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chicken_chores',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='chickenevent',
            name='chore',
            field=models.ForeignKey(blank=True, db_column='chore_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='chickens.chickenchore'),
        ),
        migrations.AddIndex(
            model_name='chickenevent',
            index=models.Index(fields=['chore', '-occurred_on'], name='idx_ck_event_chore_date'),
        ),
        migrations.AddIndex(
            model_name='chickenchore',
            index=models.Index(fields=['household', 'is_active'], name='idx_ck_chore_hh_active'),
        ),
        migrations.AddConstraint(
            model_name='chickenchore',
            constraint=models.CheckConstraint(condition=models.Q(('interval_days__gte', 1)), name='chicken_chores_interval_positive'),
        ),
    ]
