# Generated by Django 5.2.11 on 2026-07-23 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0010_household_latitude_household_location_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('condition', models.TextField(blank=True, default='')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram')], default='telegram', max_length=32)),
                ('briefing_type', models.CharField(choices=[('recurring', 'Recurring'), ('event', 'Event-driven')], default='recurring', max_length=16)),
                ('is_private', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'briefing',
                'verbose_name_plural': 'briefings',
                'db_table': 'briefings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['household', 'is_active'], name='idx_briefing_hh_active'), models.Index(fields=['created_by'], name='idx_briefing_creator')],
            },
        ),
    ]
