# Generated by Django 5.2.11 on 2026-07-24 08:39

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefings', '0001_initial'),
        ('households', '0010_household_latitude_household_location_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='send_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='briefing',
            name='weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='BriefingSendLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('slot_time', models.TimeField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('error', 'Error')], max_length=32)),
                ('content', models.TextField(blank=True, default='')),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='briefings.briefing')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefing_send_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'briefing_send_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['briefing', '-created_at'], name='idx_bsl_briefing_recent')],
                'constraints': [models.UniqueConstraint(fields=('briefing', 'user', 'slot_date', 'slot_time'), name='uniq_briefing_send_slot')],
            },
        ),
    ]
