# Generated by Django 5.2.11 on 2026-07-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefings', '0002_briefing_send_times_briefing_weekdays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefingsendlog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('error', 'Error'), ('skipped_condition', 'Skipped (condition not met)')], max_length=32),
        ),
    ]
