# Generated by Django 5.2.11 on 2026-02-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemAdmin',
        ),
    ]
