# Generated by Django 5.2.11 on 2026-02-26 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breaker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('rating_amps', models.PositiveIntegerField()),
                ('curve_type', models.CharField(blank=True, choices=[('b', 'B'), ('c', 'C'), ('d', 'D'), ('other', 'Other')], default='', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'electricity_breakers',
            },
        ),
        migrations.CreateModel(
            name='ElectricityBoard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Tableau principal', max_length=255)),
                ('supply_type', models.CharField(choices=[('single_phase', 'Single phase'), ('three_phase', 'Three phase')], max_length=20)),
                ('main_notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'electricity_boards',
            },
        ),
        migrations.CreateModel(
            name='ElectricCircuit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('phase', models.CharField(blank=True, choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3')], max_length=2, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('breaker', models.ForeignKey(db_column='breaker_id', on_delete=django.db.models.deletion.PROTECT, related_name='circuits', to='electricity.breaker')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.CASCADE, related_name='circuits', to='electricity.electricityboard')),
            ],
            options={
                'db_table': 'electricity_circuits',
            },
        ),
        migrations.AddField(
            model_name='breaker',
            name='board',
            field=models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.CASCADE, related_name='breakers', to='electricity.electricityboard'),
        ),
        migrations.CreateModel(
            name='PlanChangeLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('deactivate', 'Deactivate')], max_length=20)),
                ('entity_type', models.CharField(choices=[('board', 'Board'), ('rcd', 'RCD'), ('breaker', 'Breaker'), ('circuit', 'Circuit'), ('usage_point', 'Usage point'), ('link', 'Link')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(db_column='actor_id', on_delete=django.db.models.deletion.PROTECT, related_name='electricity_plan_changes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'electricity_plan_change_logs',
            },
        ),
        migrations.CreateModel(
            name='ResidualCurrentDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('rating_amps', models.PositiveIntegerField(blank=True, null=True)),
                ('sensitivity_ma', models.PositiveIntegerField(blank=True, null=True)),
                ('type_code', models.CharField(blank=True, choices=[('ac', 'AC'), ('a', 'A'), ('f', 'F'), ('b', 'B'), ('other', 'Other')], default='', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('board', models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.CASCADE, related_name='rcds', to='electricity.electricityboard')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'electricity_rcds',
            },
        ),
        migrations.AddField(
            model_name='breaker',
            name='rcd',
            field=models.ForeignKey(blank=True, db_column='rcd_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakers', to='electricity.residualcurrentdevice'),
        ),
        migrations.CreateModel(
            name='UsagePoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('socket', 'Socket'), ('light', 'Light')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, db_column='zone_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_usage_points', to='zones.zone')),
            ],
            options={
                'db_table': 'electricity_usage_points',
            },
        ),
        migrations.CreateModel(
            name='CircuitUsagePointLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_links_deactivated', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('circuit', models.ForeignKey(db_column='circuit_id', on_delete=django.db.models.deletion.CASCADE, related_name='usage_links', to='electricity.electriccircuit')),
                ('usage_point', models.ForeignKey(db_column='usage_point_id', on_delete=django.db.models.deletion.CASCADE, related_name='circuit_links', to='electricity.usagepoint')),
            ],
            options={
                'db_table': 'electricity_circuit_usage_links',
            },
        ),
        migrations.AddConstraint(
            model_name='electricityboard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('household',), name='uq_electricity_active_board_per_household'),
        ),
        migrations.AddConstraint(
            model_name='electriccircuit',
            constraint=models.UniqueConstraint(fields=('household', 'label'), name='uq_electricity_circuit_label_per_household'),
        ),
        migrations.AddIndex(
            model_name='planchangelog',
            index=models.Index(fields=['household', 'entity_type'], name='idx_el_chlog_hh_entity'),
        ),
        migrations.AddIndex(
            model_name='planchangelog',
            index=models.Index(fields=['household', 'created_at'], name='idx_el_chlog_hh_created'),
        ),
        migrations.AddConstraint(
            model_name='residualcurrentdevice',
            constraint=models.UniqueConstraint(fields=('household', 'label'), name='uq_electricity_rcd_label_per_household'),
        ),
        migrations.AddConstraint(
            model_name='breaker',
            constraint=models.UniqueConstraint(fields=('household', 'label'), name='uq_electricity_breaker_label_per_household'),
        ),
        migrations.AddConstraint(
            model_name='usagepoint',
            constraint=models.UniqueConstraint(fields=('household', 'label'), name='uq_electricity_usage_point_label_per_household'),
        ),
        migrations.AddConstraint(
            model_name='circuitusagepointlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('usage_point',), name='uq_electricity_active_link_per_usage_point'),
        ),
    ]
