# Generated by Django 5.2.11 on 2026-02-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breaker',
            options={'verbose_name': 'breaker', 'verbose_name_plural': 'breakers'},
        ),
        migrations.AlterModelOptions(
            name='electriccircuit',
            options={'verbose_name': 'circuit', 'verbose_name_plural': 'circuits'},
        ),
        migrations.AlterModelOptions(
            name='electricityboard',
            options={'verbose_name': 'electricity board', 'verbose_name_plural': 'electricity boards'},
        ),
        migrations.AlterModelOptions(
            name='residualcurrentdevice',
            options={'verbose_name': 'RCD', 'verbose_name_plural': 'RCDs'},
        ),
        migrations.AlterModelOptions(
            name='usagepoint',
            options={'verbose_name': 'usage point', 'verbose_name_plural': 'usage points'},
        ),
    ]
