# Generated by Django 5.2.11 on 2026-03-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0006_add_label_to_electricity_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electriccircuit',
            name='phase',
        ),
    ]
