# Generated by Django 5.2.11 on 2026-07-04 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0009_protectivedevice_position_end'),
        ('households', '0008_household_preferred_language'),
        ('zones', '0005_zone_one_root_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityMeter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('tariff_type', models.CharField(choices=[('base', 'Base'), ('hp_hc', 'Peak / off-peak')], default='base', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_meters', to='zones.zone')),
            ],
            options={
                'verbose_name': 'electricity meter',
                'verbose_name_plural': 'electricity meters',
                'db_table': 'electricity_meters',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('register', models.CharField(choices=[('base', 'Base'), ('hp', 'Peak hours'), ('hc', 'Off-peak hours')], max_length=10)),
                ('ts_start', models.DateTimeField()),
                ('interval_minutes', models.PositiveIntegerField()),
                ('energy_wh', models.PositiveBigIntegerField()),
                ('source', models.CharField(choices=[('reading', 'Meter reading'), ('import', 'Import')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(db_column='meter_id', on_delete=django.db.models.deletion.CASCADE, related_name='consumption_records', to='electricity.electricitymeter')),
            ],
            options={
                'verbose_name': 'consumption record',
                'verbose_name_plural': 'consumption records',
                'db_table': 'electricity_consumption_records',
                'indexes': [models.Index(fields=['household', 'meter', 'ts_start'], name='idx_elec_consumption_lookup')],
                'constraints': [models.UniqueConstraint(fields=('meter', 'register', 'ts_start', 'source'), name='uq_electricity_consumption_natural_key')],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('register', models.CharField(choices=[('base', 'Base'), ('hp', 'Peak hours'), ('hc', 'Off-peak hours')], max_length=10)),
                ('reading_at', models.DateTimeField()),
                ('index_kwh', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('meter', models.ForeignKey(db_column='meter_id', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='electricity.electricitymeter')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meter reading',
                'verbose_name_plural': 'meter readings',
                'db_table': 'electricity_meter_readings',
                'constraints': [models.UniqueConstraint(fields=('meter', 'register', 'reading_at'), name='uq_electricity_reading_meter_register_at')],
            },
        ),
    ]
