# Generated by Django 5.2.11 on 2026-07-07 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0011_consumptionimport_consumptionrecord_source_import'),
        ('households', '0008_household_preferred_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterTariff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField()),
                ('price_base', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('price_hp', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('price_hc', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('subscription_eur_month', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('meter', models.ForeignKey(db_column='meter_id', on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='electricity.electricitymeter')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meter tariff',
                'verbose_name_plural': 'meter tariffs',
                'db_table': 'electricity_meter_tariffs',
                'ordering': ['-valid_from'],
                'constraints': [models.UniqueConstraint(fields=('meter', 'valid_from'), name='uq_electricity_tariff_meter_valid_from')],
            },
        ),
    ]
