# Generated by Django 5.2.11 on 2026-07-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0012_metertariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitymeter',
            name='export_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
