# Generated by Django 5.2.11 on 2026-02-13 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('households', '0001_initial'),
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='interaction',
            field=models.ForeignKey(blank=True, help_text='Parent interaction (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='interactions.interaction'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['interaction'], name='idx_docs_interaction'),
        ),
    ]
