# Generated by Django 5.2.11 on 2026-02-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_interaction_document_idx_docs_interaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
    ]
