# Generated by Django 5.2.11 on 2026-03-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If True, only the uploader can see this document.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(help_text='Storage path: documents/{household_id}/{year}/{month}/{uuid}-{filename}', max_length=500),
        ),
    ]
