# Generated by Django 5.2.11 on 2026-07-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_backfill_document_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlink',
            name='phase',
            field=models.CharField(blank=True, choices=[('before', 'Before'), ('during', 'During'), ('after', 'After')], default='', max_length=16),
        ),
    ]
