# Generated by Django 5.2.11 on 2026-07-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentlink_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='taken_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Capture date read from EXIF. NULL = unknown, never a fallback.', null=True),
        ),
    ]
