# Generated by Django 5.2.11 on 2026-04-30 04:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0008_household_preferred_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('ocr_upload', 'OCR — upload'), ('ocr_backfill', 'OCR — backfill'), ('agent_ask', 'Agent — ask')], max_length=32)),
                ('provider', models.CharField(default='anthropic', max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField()),
                ('success', models.BooleanField(default=True)),
                ('error_type', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='households.household')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_usage_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['household', 'feature', '-created_at'], name='ai_usage_lo_househo_9e4366_idx'), models.Index(fields=['feature', '-created_at'], name='ai_usage_lo_feature_94bf5f_idx')],
            },
        ),
    ]
