# Generated by Django 5.2.11 on 2026-02-13 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(help_text='Storage path: userId/interactionId/filename', max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('invoice', 'Invoice'), ('manual', 'Manual'), ('warranty', 'Warranty'), ('receipt', 'Receipt'), ('plan', 'Plan'), ('certificate', 'Certificate'), ('other', 'Other')], default='document', max_length=50)),
                ('ocr_text', models.TextField(blank=True, help_text='Extracted text from OCR/processing')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Size, dimensions, processing status, etc.')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['household', 'type'], name='idx_docs_hh_type'), models.Index(fields=['created_by'], name='idx_docs_creator')],
            },
        ),
    ]
