# Generated by Django 5.2.11 on 2026-02-15 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        ('interactions', '0003_interactionstructure_structure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('interaction', 'Interaction'), ('document', 'Document'), ('contact', 'Contact'), ('structure', 'Structure')], default='interaction', max_length=50)),
                ('name', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='InteractionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_tags_created', to=settings.AUTH_USER_MODEL)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_tag_links', to='interactions.interaction')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_links', to='tags.tag')),
            ],
            options={
                'db_table': 'interaction_tags',
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['household', 'type'], name='idx_tags_hh_type'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('household', 'type', 'name')},
        ),
        migrations.AddIndex(
            model_name='interactiontag',
            index=models.Index(fields=['interaction'], name='idx_itag_interaction'),
        ),
        migrations.AddIndex(
            model_name='interactiontag',
            index=models.Index(fields=['tag'], name='idx_itag_tag'),
        ),
        migrations.AlterUniqueTogether(
            name='interactiontag',
            unique_together={('interaction', 'tag')},
        ),
    ]
