# Generated by Django 5.2.11 on 2026-07-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(db_index=True, max_length=40, unique=True)),
                ('pr_number', models.PositiveIntegerField(blank=True, null=True)),
                ('module', models.CharField(db_index=True, help_text="Scope du commit conventionnel (ex: 'projects'), ou 'general'.", max_length=50)),
                ('change_type', models.CharField(choices=[('feat', 'Nouveauté'), ('fix', 'Correction'), ('perf', 'Performance')], max_length=20)),
                ('summary', models.TextField(help_text="Phrase FR lisible, repolie par l'IA.")),
                ('raw_subject', models.TextField(help_text="Sujet du commit d'origine.")),
                ('committed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrée de changelog',
                'verbose_name_plural': 'Entrées de changelog',
                'ordering': ['-committed_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangelogState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_sha', models.CharField(max_length=40)),
                ('head_committed_at', models.DateTimeField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'État du changelog',
                'verbose_name_plural': 'État du changelog',
            },
        ),
    ]
