# Generated by Django 5.2.11 on 2026-08-15 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0012_invitation_shareable_link'),
        ('zones', '0007_alter_zone_options_zone_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('fruit_tree', 'Fruit tree'), ('berry_bush', 'Berry bush'), ('vine', 'Vine'), ('ornamental', 'Ornamental')], default='fruit_tree', max_length=20)),
                ('species', models.CharField(blank=True, default='', max_length=200)),
                ('rootstock', models.CharField(blank=True, default='', max_length=200)),
                ('planted_on', models.DateField(blank=True, null=True)),
                ('flowering_start_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('flowering_end_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('alive', 'Alive'), ('ailing', 'Ailing'), ('dead', 'Dead'), ('removed', 'Removed')], default='alive', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.PROTECT, related_name='trees', to='zones.zone')),
            ],
            options={
                'db_table': 'orchard_trees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('harvested_on', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('piece', 'pieces'), ('litre', 'litres')], default='kg', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(db_column='tree_id', on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='orchard.tree')),
            ],
            options={
                'db_table': 'orchard_harvests',
                'ordering': ['-harvested_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreeEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('pruning', 'Pruning'), ('treatment', 'Treatment'), ('fertilizing', 'Fertilizing'), ('watering', 'Watering'), ('training', 'Training'), ('observation', 'Observation'), ('flowering', 'Flowering'), ('other', 'Other')], max_length=20)),
                ('occurred_on', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('tree', models.ForeignKey(db_column='tree_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orchard.tree')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orchard_tree_events',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['household', 'status'], name='idx_tree_hh_status'),
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['zone'], name='idx_tree_zone'),
        ),
        migrations.AddConstraint(
            model_name='tree',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['alive', 'ailing', 'dead', 'removed'])), name='orchard_tree_status_check'),
        ),
        migrations.AddConstraint(
            model_name='tree',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['fruit_tree', 'berry_bush', 'vine', 'ornamental'])), name='orchard_tree_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='tree',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('flowering_end_month__isnull', True), ('flowering_start_month__isnull', True)), models.Q(('flowering_end_month__gte', 1), ('flowering_end_month__lte', 12), ('flowering_start_month__gte', 1), ('flowering_start_month__lte', 12)), _connector='OR'), name='orchard_tree_flowering_check'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['household', 'harvested_on'], name='idx_harvest_hh_date'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['tree', '-harvested_on'], name='idx_harvest_tree_date'),
        ),
        migrations.AddConstraint(
            model_name='harvest',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orchard_harvest_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='harvest',
            constraint=models.CheckConstraint(condition=models.Q(('unit__in', ['kg', 'piece', 'litre'])), name='orchard_harvest_unit_check'),
        ),
        migrations.AddIndex(
            model_name='treeevent',
            index=models.Index(fields=['household', 'occurred_on'], name='idx_tree_event_hh_date'),
        ),
        migrations.AddIndex(
            model_name='treeevent',
            index=models.Index(fields=['tree', '-occurred_on'], name='idx_tree_event_tree_date'),
        ),
    ]
