# Generated by Django 5.2.11 on 2026-08-15 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0012_invitation_shareable_link'),
        ('orchard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('emoji', models.CharField(blank=True, default='', max_length=16)),
                ('start_month', models.PositiveSmallIntegerField()),
                ('end_month', models.PositiveSmallIntegerField()),
                ('event_type', models.CharField(choices=[('pruning', 'Pruning'), ('treatment', 'Treatment'), ('fertilizing', 'Fertilizing'), ('watering', 'Watering'), ('training', 'Training'), ('observation', 'Observation'), ('flowering', 'Flowering'), ('other', 'Other')], default='pruning', max_length=20)),
                ('kind', models.CharField(blank=True, choices=[('fruit_tree', 'Fruit tree'), ('berry_bush', 'Berry bush'), ('vine', 'Vine'), ('ornamental', 'Ornamental')], default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('tree', models.ForeignKey(blank=True, db_column='tree_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_rules', to='orchard.tree')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orchard_care_rules',
                'ordering': ['start_month', 'name'],
            },
        ),
        migrations.AddField(
            model_name='treeevent',
            name='care_rule',
            field=models.ForeignKey(blank=True, db_column='care_rule_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='orchard.carerule'),
        ),
        migrations.AddIndex(
            model_name='treeevent',
            index=models.Index(fields=['care_rule', '-occurred_on'], name='idx_tree_event_rule_date'),
        ),
        migrations.AddIndex(
            model_name='carerule',
            index=models.Index(fields=['household', 'is_active'], name='idx_care_rule_hh_active'),
        ),
        migrations.AddIndex(
            model_name='carerule',
            index=models.Index(fields=['tree'], name='idx_care_rule_tree'),
        ),
        migrations.AddConstraint(
            model_name='carerule',
            constraint=models.CheckConstraint(condition=models.Q(('end_month__gte', 1), ('end_month__lte', 12), ('start_month__gte', 1), ('start_month__lte', 12)), name='orchard_rule_months_range'),
        ),
        migrations.AddConstraint(
            model_name='carerule',
            constraint=models.CheckConstraint(condition=models.Q(('tree__isnull', False), models.Q(('kind', ''), _negated=True), _negated=True), name='orchard_rule_single_scope'),
        ),
    ]
