# Generated by Django 5.2.11 on 2026-02-13 22:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.TextField(blank=True, default='')),
                ('country', models.TextField(blank=True, default='')),
                ('context_notes', models.TextField(blank=True, default='')),
                ('ai_prompt_context', models.TextField(blank=True, default='')),
                ('inbound_email_alias', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('default_household', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'households',
                'indexes': [models.Index(condition=models.Q(('city__gt', '')), fields=['city'], name='idx_hh_city'), models.Index(condition=models.Q(('country__gt', '')), fields=['country'], name='idx_hh_country'), models.Index(fields=['inbound_email_alias'], name='idx_hh_email_alias')],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=20)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'household_members',
                'indexes': [models.Index(fields=['household'], name='household_m_househo_bb3138_idx'), models.Index(fields=['user'], name='household_m_user_id_1c6f2f_idx')],
                'unique_together': {('household', 'user')},
            },
        ),
    ]
