# Generated by Django 5.2.11 on 2026-02-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='household',
            options={'verbose_name': 'household', 'verbose_name_plural': 'households'},
        ),
    ]
