# Generated by Django 5.2.11 on 2026-03-01 21:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_alter_household_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='households.household')),
                ('invited_by', models.ForeignKey(blank=True, db_column='invited_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_household_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(db_column='invited_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='household_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'household_invitations',
                'indexes': [models.Index(fields=['invited_user', 'status'], name='hhinv_user_status_idx'), models.Index(fields=['household', 'status'], name='hhinv_hh_status_idx')],
            },
        ),
    ]
