# Generated by Django 5.2.11 on 2026-04-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0007_household_postal_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English'), ('de', 'German'), ('es', 'Spanish')], default='fr', max_length=2),
        ),
    ]
