# Generated by Django 5.2.11 on 2026-07-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0008_household_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='disabled_modules',
            field=models.JSONField(blank=True, default=list, help_text='Optional module keys hidden for this household.'),
        ),
    ]
