# Generated by Django 5.2.11 on 2026-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0009_household_disabled_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude for the weather module (decimal degrees).', null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='location_label',
            field=models.CharField(blank=True, default='', help_text='Human-readable place name shown in the weather module.', max_length=255),
        ),
        migrations.AddField(
            model_name='household',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude for the weather module (decimal degrees).', null=True),
        ),
    ]
