# Generated by Django 5.2.11 on 2026-02-15 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_interaction_document_idx_docs_interaction'),
        ('households', '0001_initial'),
        ('interactions', '0003_interactionstructure_structure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.TextField()),
                ('from_email', models.TextField()),
                ('from_name', models.TextField(default='')),
                ('to_email', models.TextField()),
                ('subject', models.TextField(default='')),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_emails_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_emails', to='households.household')),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_emails', to='interactions.interaction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_emails_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incoming_emails',
            },
        ),
        migrations.CreateModel(
            name='IncomingEmailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('content_type', models.TextField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('content_base64', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_email_attachments', to='documents.document')),
                ('incoming_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incoming_emails.incomingemail')),
            ],
            options={
                'db_table': 'incoming_email_attachments',
            },
        ),
        migrations.AddIndex(
            model_name='incomingemail',
            index=models.Index(fields=['household', 'processing_status'], name='idx_inmail_hh_status'),
        ),
        migrations.AddIndex(
            model_name='incomingemail',
            index=models.Index(fields=['message_id'], name='idx_inmail_message'),
        ),
    ]
