# Generated by Django 5.2.11 on 2026-02-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'zone', 'verbose_name_plural': 'zones'},
        ),
    ]
