# Generated by Django 5.2.11 on 2026-04-28 19:50

from django.conf import settings
from django.db import migrations


def normalize_root_zones(apps, schema_editor):
    """Garantit qu'avant la contrainte, chaque household a 0 ou 1 zone racine.

    - Pour chaque household avec plusieurs racines : on garde la plus ancienne,
      les autres deviennent ses enfants.
    - Pour chaque household sans racine : on en crée une ('Maison').
    """
    Household = apps.get_model('households', 'Household')
    Zone = apps.get_model('zones', 'Zone')

    for household in Household.objects.all():
        roots = list(
            Zone.objects.filter(household=household, parent__isnull=True)
            .order_by('created_at', 'id')
        )
        if len(roots) == 0:
            Zone.objects.create(household=household, name='Maison')
        elif len(roots) > 1:
            primary = roots[0]
            for other in roots[1:]:
                other.parent = primary
                other.save(update_fields=['parent'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0007_household_postal_timezone'),
        ('zones', '0003_add_zone_color_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_root_zones, reverse_noop),
    ]
