# Generated by Django 5.2.11 on 2026-07-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0005_zone_one_root_constraint'),
        ('documents', '0006_backfill_document_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZoneDocument',
        ),
    ]
