# Generated by Django 5.2.11 on 2026-07-27 13:21

from django.conf import settings
from django.db import migrations, models
from django.db.models.functions import Lower


def seed_positions(apps, schema_editor):
    """Fige l'ordre alphabétique existant dans `position`.

    Le backfill vit dans la même migration que l'ajout du champ : avec tous les
    rangs à `0`, `ordering = ['position', 'name']` retomberait sur `name` — donc
    rien ne bougerait à l'écran, mais le premier réordonnancement d'une fratrie
    ferait sauter toutes les autres d'un ordre implicite à un ordre explicite.
    On part donc de ce que l'utilisateur voit aujourd'hui.

    `Lower(name)` reproduit le tri insensible à la casse du front
    (`localeCompare` avec `sensitivity: 'base'`) au plus près de ce que SQL sait
    faire — l'objectif est qu'aucun foyer ne voie ses zones se réorganiser au
    déploiement.
    """
    Zone = apps.get_model('zones', 'Zone')

    groups = {}
    for zone in Zone.objects.all().order_by('household_id', 'parent_id', Lower('name'), 'name'):
        groups.setdefault((zone.household_id, zone.parent_id), []).append(zone)

    to_update = []
    for siblings in groups.values():
        for index, zone in enumerate(siblings):
            if zone.position != index:
                zone.position = index
                to_update.append(zone)

    if to_update:
        Zone.objects.bulk_update(to_update, ['position'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0011_retire_banking_module_key'),
        ('zones', '0006_delete_zonedocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['position', 'name'], 'verbose_name': 'zone', 'verbose_name_plural': 'zones'},
        ),
        migrations.AddField(
            model_name='zone',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['parent', 'position'], name='idx_zone_parent_position'),
        ),
        # `elidable=False` : le rang est une donnée, pas un état dérivable — un
        # squash qui sauterait ce backfill laisserait la prod à zéro partout.
        migrations.RunPython(seed_positions, migrations.RunPython.noop, elidable=False),
    ]
