# Generated by Django 5.2.11 on 2026-02-13 22:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('surface', models.DecimalField(blank=True, decimal_places=2, help_text='Surface area (e.g., square meters)', max_digits=10, null=True)),
                ('color', models.CharField(default='#f4f4f5', help_text='Hex color code for zone display', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code (e.g., #f4f4f5)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='zones.zone')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zones',
            },
        ),
        migrations.CreateModel(
            name='ZoneDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='photo', help_text="Role of document (typically 'photo')", max_length=50)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('zone', models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.CASCADE, to='zones.zone')),
            ],
            options={
                'db_table': 'zone_documents',
            },
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['household', 'parent'], name='zones_househo_b3fc81_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['parent'], name='zones_parent__d9c5f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.CheckConstraint(condition=models.Q(('surface__gte', 0), ('surface__isnull', True), _connector='OR'), name='zones_surface_check'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('id', 'household')},
        ),
        migrations.AddIndex(
            model_name='zonedocument',
            index=models.Index(fields=['zone'], name='zone_docume_zone_id_7fc2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='zonedocument',
            index=models.Index(fields=['document'], name='zone_docume_documen_79474c_idx'),
        ),
        migrations.AddIndex(
            model_name='zonedocument',
            index=models.Index(fields=['-created_at'], name='idx_zone_docs_created'),
        ),
        migrations.AlterUniqueTogether(
            name='zonedocument',
            unique_together={('zone', 'document')},
        ),
    ]
