# Generated by Django 5.2.11 on 2026-07-25 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0010_household_latitude_household_location_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('bank_label', models.CharField(blank=True, default='', help_text='Bank name, free text. Empty for a cash account.', max_length=120)),
                ('kind', models.CharField(choices=[('bank', 'Bank account'), ('cash', 'Cash')], default='bank', max_length=8)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('iban_last4', models.CharField(blank=True, default='', help_text='Last 4 characters of the IBAN, to tell two accounts apart. The full IBAN is NEVER stored.', max_length=4)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text="Balance at 'opening_balance_date'. Starting point of the derived balance computation; may be negative (overdraft).", max_digits=14)),
                ('opening_balance_date', models.DateField(blank=True, help_text='Date the opening balance refers to. Null = not set yet.', null=True)),
                ('default_provider', models.CharField(blank=True, default='', help_text='Statement importer key remembered from the last import (lot 2).', max_length=50)),
                ('import_options', models.JSONField(blank=True, default=dict, help_text="Column mapping remembered for this bank's export, so the format is described once and not at every import (lot 2).")),
                ('archived', models.BooleanField(default=False, help_text='Closed account: hidden from the default list, never deleted.')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bank account',
                'verbose_name_plural': 'bank accounts',
                'db_table': 'bank_accounts',
                'ordering': ['archived', 'name'],
                'indexes': [models.Index(fields=['household', 'archived'], name='idx_bankacct_hh_arch')],
                'constraints': [models.UniqueConstraint(fields=('household', 'name'), name='uq_bank_account_name_per_hh')],
            },
        ),
    ]
