# Generated by Django 5.2.11 on 2026-07-26 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('households', '0010_household_latitude_household_location_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementImport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(blank=True, default='', help_text='Importer key used (e.g. generic_csv). Empty when unrecognized.', max_length=50)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=10)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0, help_text='Lines already present — the normal outcome of a re-import.')),
                ('error', models.TextField(blank=True, default='')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='banking.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'statement import',
                'verbose_name_plural': 'statement imports',
                'db_table': 'bank_statement_imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booked_on', models.DateField(help_text='Operation date as printed on the statement.')),
                ('value_on', models.DateField(blank=True, help_text='Value date, when provided.', null=True)),
                ('label_raw', models.CharField(editable=False, help_text='Raw bank label. Never rewritten.', max_length=500)),
                ('label_norm', models.CharField(default='', editable=False, help_text='Normalized label: feeds the dedup hash and the lot 6 matcher.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: negative = money out.', max_digits=14)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('direction', models.CharField(choices=[('out', 'Money out'), ('in', 'Money in')], max_length=3)),
                ('is_internal', models.BooleanField(default=False, help_text="Internal movement (ATM withdrawal, transfer between the household's own accounts). Excluded from spending aggregates — counting it would double the money.")),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, help_text='Running balance after this operation, when the bank exports it. Anchors the lot 4 balance and its chain check.', max_digits=14, null=True)),
                ('external_id', models.CharField(blank=True, default='', help_text='Bank-provided operation reference, when available.', max_length=64)),
                ('dedup_hash', models.CharField(editable=False, help_text='Natural key of the line. Set once at creation and NEVER recomputed: re-hashing after a label cleanup would resurrect duplicates.', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(help_text='PROTECT: an account holding transactions cannot be deleted — it is archived instead (see services.archive_account).', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='banking.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('source_import', models.ForeignKey(blank=True, help_text='SET_NULL: transactions outlive the trace of their import.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='banking.statementimport')),
            ],
            options={
                'verbose_name': 'bank transaction',
                'verbose_name_plural': 'bank transactions',
                'db_table': 'bank_transactions',
                'ordering': ['-booked_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='statementimport',
            index=models.Index(fields=['household', '-created_at'], name='idx_stmtimp_hh_created'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['household', 'booked_on'], name='idx_bank_txn_hh_date'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['account', 'booked_on'], name='idx_bank_txn_acct_date'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['household', 'direction', 'is_internal'], name='idx_bank_txn_hh_dir'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(fields=('account', 'dedup_hash'), name='uq_bank_txn_account_dedup'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='bank_txn_amount_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__lt', 0), ('direction', 'out')), models.Q(('amount__gt', 0), ('direction', 'in')), _connector='OR'), name='bank_txn_direction_matches_sign'),
        ),
    ]
