# Generated by Django 5.2.11 on 2026-07-26 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_statementimport_banktransaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ['-booked_on', '-line_no', '-created_at'], 'verbose_name': 'bank transaction', 'verbose_name_plural': 'bank transactions'},
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='line_no',
            field=models.PositiveIntegerField(default=0, help_text="Row position in the source file. Two operations booked the same day must keep the statement's own order, otherwise the balance chain check (banking.balances) cannot tell which balance follows which — and 'created_at' is not dependable for that after a bulk_create."),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='transfer_counterpart',
            field=models.OneToOneField(blank=True, help_text='The other leg of an internal movement — typically an ATM withdrawal and the matching credit on the cash account. SET_NULL so deleting one leg never leaves the other pointing at nothing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterpart_of', to='banking.banktransaction'),
        ),
    ]
