# Generated by Django 5.2.11 on 2026-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_banktransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementimport',
            name='auto_matched_count',
            field=models.PositiveIntegerField(default=0, help_text='Lines this import reconciled by itself with expenses already typed into the app (lot 6). The number the user actually cares about: it is what they did NOT have to sort out by hand.'),
        ),
    ]
