# Generated by Django 5.2.11 on 2026-07-26 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_statementimport_auto_matched_count'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('households', '0010_household_latitude_household_location_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceWaiver',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_kind', models.CharField(help_text='Detector key from banking.compliance.REGISTRY.', max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('reason', models.TextField(help_text='Why this écart is acceptable. Required: an arbitration without a motive is indistinguishable from hiding the problem.')),
                ('fingerprint', models.CharField(help_text='State of the écart when it was arbitrated. When it no longer matches, the waiver is stale and the écart resurfaces.', max_length=64)),
                ('content_type', models.ForeignKey(help_text='Model of the object being arbitrated.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'compliance waiver',
                'verbose_name_plural': 'compliance waivers',
                'db_table': 'banking_compliance_waivers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['household', 'finding_kind'], name='idx_waiver_hh_kind')],
                'constraints': [models.UniqueConstraint(fields=('household', 'finding_kind', 'content_type', 'object_id'), name='uq_waiver_per_finding_object')],
            },
        ),
    ]
