# Generated by Django 5.2.11 on 2026-07-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_compliancewaiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='inflow_nature',
            field=models.CharField(blank=True, choices=[('salary', 'Income'), ('refund', 'Refund'), ('transfer', 'Transfer between own accounts'), ('other', 'Other')], default='', help_text='What this receipt is (parcours 26, lot 5). Empty on an outflow, and empty on an unclassified receipt — which is an écart the conformity control reports.', max_length=10),
        ),
    ]
