# Generated by Django 5.2.11 on 2026-07-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_banktransaction_inflow_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='attested_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Balance the user read on their bank at 'attested_on', used to reconstruct 'opening_balance' by subtracting the movements in between. Kept so the arithmetic can be re-checked forever after (parcours 26, lot 8) — banks that export no balance column give us no other anchor.", max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='attested_on',
            field=models.DateField(blank=True, help_text="Date 'attested_balance' was read. Null = never attested.", null=True),
        ),
    ]
