# Generated by Django 5.2.11 on 2026-07-27 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_bankaccount_attested_balance_bankaccount_attested_on'),
        ('budget', '0004_alter_budget_monthly_amount'),
        ('households', '0011_retire_banking_module_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='refund_budget',
            field=models.ForeignKey(blank=True, help_text="Budget this refund credits back. Only meaningful on an inflow classified `refund`: returning a 40 € item means the envelope consumed 110 € of the 150 € spent, not 150 €. Kept here rather than as a negative Interaction — `Interaction.amount` never goes negative, which is what protects the nine Sum('amount') aggregations. SET_NULL: deleting a budget must never destroy a bank line.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='budget.budget'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('refund_budget__isnull', True), ('inflow_nature', 'refund'), _connector='OR'), name='bank_txn_refund_budget_only_on_refund'),
        ),
    ]
