# Generated by Django 5.2.11 on 2026-07-28 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_banktransaction_refund_budget_and_more'),
        ('budget', '0005_budget_parent'),
        ('households', '0011_retire_banking_module_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive: what this envelope gets back, never a signed amount.', max_digits=14)),
                ('budget', models.ForeignKey(help_text='CASCADE too: a credit to an envelope that no longer exists is not a fact worth keeping — unlike the bank line itself, which survives everything.', on_delete=django.db.models.deletion.CASCADE, related_name='refund_allocations', to='budget.budget')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('transaction', models.ForeignKey(help_text='CASCADE: the bank line is the fact, its credits are a reading of it. Deleting the line must not leave envelopes credited by nothing.', on_delete=django.db.models.deletion.CASCADE, related_name='refund_allocations', to='banking.banktransaction')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'refund allocation',
                'verbose_name_plural': 'refund allocations',
                'db_table': 'bank_refund_allocations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['budget'], name='idx_refund_alloc_budget')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_allocation_amount_positive'), models.UniqueConstraint(fields=('transaction', 'budget'), name='one_refund_allocation_per_budget')],
            },
        ),
    ]
