# Generated by Django 5.2.11 on 2026-07-16 21:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0010_household_latitude_household_location_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_global', models.BooleanField(default=False, help_text='The single household-wide budget that caps all expenses (budgeted + hors budget). At most one per household.')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'budget',
                'verbose_name_plural': 'budgets',
                'db_table': 'budgets',
                'ordering': ['-is_global', 'name'],
                'indexes': [models.Index(fields=['household', 'is_global'], name='idx_budget_hh_global')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_global', True)), fields=('household',), name='one_global_budget_per_household'), models.UniqueConstraint(fields=('household', 'name'), name='unique_budget_name_per_household')],
            },
        ),
    ]
