# Generated by Django 5.2.11 on 2026-07-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budgetreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Monthly ceiling. NULL = tracked category with no ceiling — the counters still add up what it spent, nothing is ever 'over'. Required on the global budget, which exists only to cap.", max_digits=12, null=True),
        ),
    ]
