# Generated by Django 5.2.11 on 2026-07-27 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_budget_monthly_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Optional grouping budget: « Maison » over « Bricolage » and « Énergie ». A parent is a SUBTOTAL, never a target — an expense always lands on a leaf, so 'budget' keeps meaning exactly one thing and the nine amount aggregations keep their definition. Two levels only, and SET_NULL: deleting a group must free its children, never destroy the envelopes that carry the money.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='budget.budget'),
        ),
    ]
