# Generated by Django 5.2.11 on 2026-07-29 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_budget_parent'),
        ('households', '0011_retire_banking_module_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Deprecated — superseded by `category`. Dropped next release.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='budget.budget'),
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('monthly_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional monthly ceiling for the whole category. NULL = pure subtotal, worth the sum of the budgets it holds. When set, it REPLACES that sum — adding both would count the same commitment twice and cry overshoot at a perfectly coherent household.', max_digits=12, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'budget category',
                'verbose_name_plural': 'budget categories',
                'db_table': 'budget_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional category this envelope is filed under. SET_NULL: deleting a category is deleting a heading, and a heading that disappears must never take the envelopes that carry the money with it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='budget.budgetcategory'),
        ),
        migrations.AddConstraint(
            model_name='budgetcategory',
            constraint=models.UniqueConstraint(fields=('household', 'name'), name='unique_budget_category_name_per_household'),
        ),
    ]
