# Generated by Django 5.2.11 on 2026-07-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('household_invitation', 'Household invitation'), ('household_member_joined', 'New household member'), ('stock_low', 'Low stock'), ('stock_out', 'Out of stock')], max_length=64),
        ),
    ]
