# Generated by Django 5.2.11 on 2026-07-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Caller-chosen identity of the fact announced. A second notification with the same (user, type, key) is skipped while the first is alive.', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, default='', help_text="In-app path this notification leads to. Per-row and not per-type: 'Bob finished Mow the lawn' points at that task, which a map keyed by type cannot express.", max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('household_invitation', 'Household invitation'), ('household_member_joined', 'New household member'), ('stock_low', 'Low stock'), ('stock_out', 'Out of stock'), ('weather_alert', 'Weather alert')], max_length=64),
        ),
    ]
