# Generated by Django 5.2.11 on 2026-08-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_dedup_key_notification_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('household_invitation', 'Household invitation'), ('household_member_joined', 'New household member'), ('stock_low', 'Low stock'), ('stock_out', 'Out of stock'), ('weather_alert', 'Weather alert'), ('chicken_chore_due', 'Coop chore due'), ('hunt_suggestion', 'Treasure hunt suggestion')], max_length=64),
        ),
    ]
