# Generated by Django 5.2.11 on 2026-08-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('household_invitation', 'Household invitation'), ('household_member_joined', 'New household member'), ('task_created', 'New task'), ('note_created', 'New note'), ('stock_low', 'Low stock'), ('stock_out', 'Out of stock'), ('weather_alert', 'Weather alert'), ('chicken_chore_due', 'Coop chore due'), ('hunt_suggestion', 'Treasure hunt suggestion')], max_length=64),
        ),
    ]
